// src/gatePassToken/dto/create-token.dto.ts
import {
  IsString,
  IsNotEmpty,
  IsEnum,
  IsDate,
  IsOptional,
  IsBoolean,
  IsNumber,
  Min,
  IsMongoId,
} from 'class-validator';
import { Type } from 'class-transformer';
import { TokenType, VisitorType } from '../entities/token.entity';

export class CreateTokenDto {
  @IsOptional()
  @IsString()
  token?: string; // Optional as it can be generated by the service

  // @IsNotEmpty()
  // @IsEnum(TokenType)
  // type: TokenType = TokenType.GATE_PASS;

  @IsNotEmpty()
  @IsString()
  visitorName: string;

  @IsOptional()
  @IsEnum(VisitorType)
  visitorType?: VisitorType = VisitorType.OTHER;

  @IsOptional()
  @IsNumber()
  @Min(1)
  @Type(() => Number)
  numberOfVisitors?: number = 1;

  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  hasCar?: boolean = false;

  @IsOptional()
  @IsString()
  carPlateNumber?: string;

  @IsOptional()
  @IsString()
  carModel?: string;

  @IsOptional()
  @IsString()
  carColor?: string;

  @IsOptional()
  @IsString()
  purpose?: string;

  @IsNotEmpty()
  @IsMongoId()
  estate: string;

  @IsOptional()
  @IsMongoId()
  property?: string;

  @IsOptional()
  @IsString()
  meansOfId?: string;

  @IsOptional()
  @IsString()
  idImgUrl?: string;

  @IsOptional()
  @IsDate()
  @Type(() => Date)
  expiresAt?: Date; // Optional as it can be set by the service

  @IsOptional()
  @IsBoolean()
  used?: boolean;

  @IsOptional()
  @IsBoolean()
  @Type(() => Boolean)
  verifyVisitor?: boolean = false;
}
